get http://localhost:8000/sanctum/csrf-cookie


###
get http://localhost:8000/api/user
Accept: application/json
X-XSRF-TOKEN: 'eyJpdiI6IjZoY1YrOGpabGh0cjliMXNybnQ3bGc9PSIsInZhbHVlIjoiOE43TkZsamN0VnlJMXRqMnBsS1ZKYW82cldBUWpDTzFkNTRrY2h5ejRKa0QwZisrMEh3ZG5hVGtSa1lwa0UxUjFwYXFNN2dCaFU3U1h3UGM2RWdLNkF1YW9RMm9nM1VMQUR2OVhGRWZMRlZFTms4elBmSnpNZDdpT1AvUGE1dHkiLCJtYWMiOiJkYzIyYmJkOTk5N2NlZjYwZWFlMTgwMGJjZWJjMzFlYmIyMmI3OWJkMmUzNjk5YzFjZTQzYjQ1MGYxNTBlMmI4In0%3D; expires=Wed, 05-Jul-2023 09:03:16 GMT; Max-Age=7200; path=/; samesite=lax,aplikasi_percepat_session=eyJpdiI6InpDbXcyK1FxVVY1ZE05ZEhja2hNTnc9PSIsInZhbHVlIjoiWkNPUUlnQVJVdThXYkcrS1ZJRTdTaThnQk9WcnRtcDJtb0VtcEc4ZXU3ZFBHZmRJTXo3V1VSd1JSUUQyZUp0VlN6enRXa1Z6Z2Nzb1NiQlRyYm94NzZTSWxEK1k4dnJ5Q3pueHQ3YkZKVW54ZVlUMnkxcmZQcDQ0VkR0NlY1REEiLCJtYWMiOiJiOWUzNTg4Y2Y3NWFkNjg2ZTQ1YzY1NWUzZDcxYjAyODM2YjMyZDkzZjQ1NmM4NGI1NGZjODliOTUzZmJlZTYzIn0%3D'

###
post http://localhost:8000/login
Accept: application/json
X-XSRF-TOKEN: 'eyJpdiI6Iiszc1JweDNuZEI1eklEbWFwek5ISVE9PSIsInZhbHVlIjoiSlVTMUpPR1d0Zk1MUUx6ZnBIMXZvcU9najFGblYxbGlQejdqZ1VUKzhldTBDSytyVm51RUQ0dm9vMXU1TmVsd1VoL1R0T1loSDMvd0Q4K3pLRXJsZEh3YXhFclFWWXJzMHRpTk81L0gyOURXcFpYM2ozRG1YR0NXRnVrYWIzdUgiLCJtYWMiOiJkM2I2MWQzM2I4NWYzNDM1NTRjNWVjMmE5YzZlODA2NTU0NWI3OTcxNTU4OTQwZWI0ZTQ1ZGI4MzM4MzI1M2RhIn0%3D; expires=Thu, 06-Jul-2023 02:35:51 GMT; Max-Age=7200; path=/; samesite=lax,aplikasi_percepat_session=eyJpdiI6IlJsSDVIdldldXppaW9lNE9sVzgrc2c9PSIsInZhbHVlIjoiZFhZRmxPQjNPN1NoYWFQc1dtaU04SlZ5VXhzUFlicDRpL2t3M2FucjZVT21TalhpYkZsRlVqRy9YV2tPaUJKd2sycHhCZUlKVm9ocjRwbkI5eTZzMXBLMVhYV0lDbDRqTmdVYU94aGczeFU1RTB5ekRVMjkrd2NiWHkzYlhxRy8iLCJtYWMiOiI1ODE5MGE0NTE5ZWM0ZGUyNzI3NGYyN2M0ZTlhYmM4OWY5MWYzNTk5YTFiMDM4Mzk1ZDU0NmI2ODQ5MzI2MmM3In0%3D;'
