name: Deploy to percepat-api.bbpommataram.id

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 56710
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "[Deploy] Fetch latest code..."
            APP_DIR=/home/bbpommataram.id/PERCEPAT-API
            PHP_BIN=/usr/local/lsws/lsphp82/bin/php
            COMPOSER_BIN=/usr/bin/composer

            cd $APP_DIR || exit
            git fetch --all
            git reset --hard origin/master

            echo "[Deploy] Install dependencies..."
            export COMPOSER_ALLOW_SUPERUSER=1
            $PHP_BIN $COMPOSER_BIN install \
            --no-dev \
            --prefer-dist \
            --no-interaction \
            --optimize-autoloader

            echo "[Deploy] Run migrations..."
            $PHP_BIN artisan migrate --force

            echo "[Deploy] Clear caches..."
            $PHP_BIN artisan optimize:clear

            echo "[Deploy] Fix permissions..."

            chown -R bbpom9725:bbpom9725 $APP_DIR/storage $APP_DIR/bootstrap/cache

            find $APP_DIR/storage -type d -exec chmod 755 {} \;
            find $APP_DIR/bootstrap/cache -type d -exec chmod 755 {} \;

            find $APP_DIR/storage -type f -exec chmod 644 {} \;
            find $APP_DIR/bootstrap/cache -type f -exec chmod 644 {} \;

            touch $APP_DIR/storage/logs/laravel.log
            chown bbpom9725:bbpom9725 $APP_DIR/storage/logs/laravel.log
            chmod 644 $APP_DIR/storage/logs/laravel.log

            echo "[Deploy] Done ✅"
